import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '../styles/Home.module.scss'
import { Button } from "antd";
import { DeleteFilled } from '@ant-design/icons';
import { useRouter } from "next/router";

const inter = Inter({ subsets: ['latin', 'cyrillic'] })

export default function Home() {
  const router = useRouter();
  const styleButtons = { marginBottom: "0.5rem", borderRadius: "5px" };
  return (
    // <div className={styles.generalBodyContent}>
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="description" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 style={{ color: "white" }}>Hello World</h1>
        <div>
          <Button
            onClick={()=> window.open("https://github.com/Vitalii505/smart_weather_app")}
            color='inherit'
            key="github"
            style={styleButtons}>
                <DeleteFilled />
                GitHub
        </Button>,
        <Button
            onClick={async ()=> router.push("/dashboard")}
            color='inherit'
            key="three"
            style={styleButtons}>
            <DeleteFilled />
            Login
        </Button>,
        </div>
      </main>
    </>
  )
}
